df <- d %>%
  summarise(`Conspiracy Belief (1)` = round(sum(is.na(cb1))/n(),2),
            `Conspiracy Belief (2)` = round(sum(is.na(cb2))/n(),2),
            `Conspiracy Belief (3)` = round(sum(is.na(cb3))/n(),2),
            `Conspiracy Belief (4)` = round(sum(is.na(cb4))/n(),2),
            `Conspiracy Belief (5)` = round(sum(is.na(cb5))/n(),2),
            `Economic Elite Conspiracy Belief (1)` = round(sum(is.na(cl1))/n(),2),
            `Economic Elite Conspiracy Belief (2)` = round(sum(is.na(cl2))/n(),2),
            `Economic Elite Conspiracy Belief (3)` = round(sum(is.na(cl3))/n(),2),
            `Economic Elite Conspiracy Belief (4)` = round(sum(is.na(cl4))/n(),2),
            `Political Cultural Conspiracy Belief (1)` = round(sum(is.na(cr1))/n(),2),
            `Political Cultural Conspiracy Belief (2)` = round(sum(is.na(cr2))/n(),2),
            `Political Cultural Conspiracy Belief (3)` = round(sum(is.na(cr3))/n(),2),
            `Political Cultural Conspiracy Belief (4)` = round(sum(is.na(cr4))/n(),2),
            `Age` = round(sum(is.na(age))/n(),2),
            `Gender` = round(sum(is.na(gender))/n(),2),
            `Education` = round(sum(is.na(education))/n(),2),
            `Ideology` = round(sum(is.na(ideology))/n(),2)) %>%
  pivot_longer(cols = `Conspiracy Belief (1)`:`Ideology`,
               names_to = "Variables", values_to = "% Missing Values")

means <- d %>%
  summarise(cb1 = round(mean(cb1, na.rm = T),0),
            cb2 = round(mean(cb2, na.rm = T),0),
            cb3 = round(mean(cb3, na.rm = T),0),
            cb4 = round(mean(cb4, na.rm = T),0),
            cb5 = round(mean(cb5, na.rm = T),0),
            cl1 = round(mean(cl1, na.rm = T),0),
            cl2 = round(mean(cl2, na.rm = T),0),
            cl3 = round(mean(cl3, na.rm = T),0),
            cl4 = round(mean(cl4, na.rm = T),0),
            cr1 = round(mean(cr1, na.rm = T),0),
            cr2 = round(mean(cr2, na.rm = T),0),
            cr3 = round(mean(cr3, na.rm = T),0),
            cr4 = round(mean(cr4, na.rm = T),0),
            age = round(mean(age, na.rm = T),0),
            gender = max(names(table(gender))),
            ideology = round(mean(ideology, na.rm = T),0),
            education = round(mean(education, na.rm = T),0))

d <- d %>%
  mutate(cb1 = ifelse(is.na(cb1), means$cb1, cb1),
         cb2 = ifelse(is.na(cb2), means$cb2, cb2),
         cb3 = ifelse(is.na(cb3), means$cb3, cb3),
         cb4 = ifelse(is.na(cb4), means$cb4, cb4),
         cb5 = ifelse(is.na(cb5), means$cb5, cb5),
         cl1 = ifelse(is.na(cl1), means$cl1, cl1),
         cl2 = ifelse(is.na(cl2), means$cl2, cl2),
         cl3 = ifelse(is.na(cl3), means$cl3, cl3),
         cl4 = ifelse(is.na(cl4), means$cl4, cl4),
         cr1 = ifelse(is.na(cr1), means$cr1, cr1),
         cr2 = ifelse(is.na(cr2), means$cr2, cr2),
         cr3 = ifelse(is.na(cr3), means$cr3, cr3),
         cr4 = ifelse(is.na(cr4), means$cr4, cr4),
         ideology = ifelse(is.na(ideology), means$ideology, ideology),
         age = ifelse(is.na(age), means$age, age),
         gender = ifelse(gender == "NA", means$gender, gender),
         education = ifelse(is.na(education), means$education, education))

