#Dummy for missing
mis1 <- df %>% 
  filter(wave==1) %>% 
  group_by(country) %>% 
  summarise_all(~ sum(is.na(.))) %>% 
  pivot_longer(cols = picom1:pop7)  %>% 
  filter(value < 1000) %>% 
  mutate(tot = ifelse(country == "DE", 1003,
               ifelse(country == "PL", 1003,
               ifelse(country == "SP", 1000,
               ifelse(country == "SW", 1005, 1002)))),
         perc = value/tot,
         wave = 1) %>% 
  filter(perc > 0.1) %>% 
  select(wave, country, name, perc) %>% 
  pivot_wider(names_from = name,
              values_from = perc)

##Dummy for missing
mis2 <- df %>% 
  filter(wave==2) %>% 
  group_by(country) %>% 
  summarise_all(~ sum(is.na(.))) %>% 
  pivot_longer(cols = picom1:pop7)  %>% 
  filter(value < 1000) %>% 
  mutate(tot = ifelse(country == "FR", 1016,
               ifelse(country == "IT", 1002,
               ifelse(country == "SP", 1012,
               ifelse(country == "SW", 1009, 1003)))),
         perc = value/tot,
         wave = 2) %>% 
  filter(perc > 0.1) %>% 
  select(wave, country, name, perc) %>% 
  pivot_wider(names_from = name,
              values_from = perc)

#Inputing mean/median + dummy
mis <- colnames(bind_rows(mis1, mis2)) #52 vars
rm(mis1, mis2)

df <- df %>% 
  mutate(missing_conspiracycovid1 = case_when(is.na(conspiracycovid1) ~ 1,
                                              TRUE ~ 0),
         missing_conspiracycovid2 = case_when(is.na(conspiracycovid2) ~ 1,
                                             TRUE ~ 0),
         missing_conspiracycovid3 = case_when(is.na(conspiracycovid3) ~ 1,
                                              TRUE ~ 0),
         missing_conspiracycovid4 = case_when(is.na(conspiracycovid4) ~ 1,
                                              TRUE ~ 0),
         missing_pid = case_when(is.na(pid) ~ 1,
                                              TRUE ~ 0),
         missing_ideology_selfplacement = case_when(is.na(ideology_selfplacement) ~ 1,
                                 TRUE ~ 0),
         missing_ideology_placement_party1 = case_when(is.na(ideology_placement_party1) ~ 1,
                                 TRUE ~ 0),
         missing_ideology_placement_party2 = case_when(is.na(ideology_placement_party2) ~ 1,
                                 TRUE ~ 0),
         missing_ideology_placement_party3 = case_when(is.na(ideology_placement_party3) ~ 1,
                                 TRUE ~ 0),
         missing_ideology_placement_party4 = case_when(is.na(ideology_placement_party4) ~ 1,
                                                       TRUE ~ 0),
         missing_ideology_placement_party5 = case_when(is.na(ideology_placement_party5) ~ 1,
                                                       TRUE ~ 0),
         missing_ideology_placement_party6 = case_when(is.na(ideology_placement_party6) ~ 1,
                                                       TRUE ~ 0),
         missing_eu_perf_econ = case_when(is.na(eu_perf_econ) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_freedom_econ = case_when(is.na(tradeof_freedom_econ) ~ 1,
                                                    TRUE ~ 0),
         missing_tradeof_health_econ_party1 = case_when(is.na(tradeof_health_econ_party1) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_health_econ_party2 = case_when(is.na(tradeof_health_econ_party2) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_health_econ_party3= case_when(is.na(tradeof_health_econ_party3) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_health_econ_party4 = case_when(is.na(tradeof_health_econ_party4) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_health_econ_party5 = case_when(is.na(tradeof_health_econ_party5) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_health_econ_party6 = case_when(is.na(tradeof_health_econ_party6) ~ 1,
                                                       TRUE ~ 0),
         missing_tradeof_health_jobs = case_when(is.na(tradeof_health_jobs) ~ 1,
                                          TRUE ~ 0),
         missing_tradeof_health_freedom = case_when(is.na(tradeof_health_freedom) ~ 1,
                                                 TRUE ~ 0),
         missing_beneficiaries_covid_measures = case_when(is.na(beneficiaries_covid_measures) ~ 1,
                                                 TRUE ~ 0),
         missing_covid_measures_constitutional = case_when(is.na(covid_measures_constitutional) ~ 1,
                                                    TRUE ~ 0),
         missing_covid_solidarity_division = case_when(is.na(covid_solidarity_division) ~ 1,
                                                 TRUE ~ 0),
         missing_role_state_economy = case_when(is.na(role_state_economy) ~ 1,
                                                    TRUE ~ 0),
         missing_friend_enemy_USA = case_when(is.na(friend_enemy_USA) ~ 1,
                                                          TRUE ~ 0),
         missing_friend_enemy_CHINA = case_when(is.na(friend_enemy_CHINA) ~ 1,
                                                           TRUE ~ 0),
         missing_friend_enemy_RUSSIA = case_when(is.na(friend_enemy_RUSSIA) ~ 1,
                                              TRUE ~ 0),
         missing_econ_immigration = case_when(is.na(econ_immigration) ~ 1,
                                                TRUE ~ 0),
         missing_cult_immigration = case_when(is.na(cult_immigration) ~ 1,
                                              TRUE ~ 0),
         missing_impact_climate = case_when(is.na(impact_climate) ~ 1,
                                              TRUE ~ 0),
         missing_ptv_party1 = case_when(is.na(ptv_party1) ~ 1,
                                                           TRUE ~ 0),
         missing_ptv_party2 = case_when(is.na(ptv_party2) ~ 1,
                                                       TRUE ~ 0),
         missing_ptv_party3 = case_when(is.na(ptv_party3) ~ 1,
                                                TRUE ~ 0),
         missing_ptv_party4 = case_when(is.na(ptv_party4) ~ 1,
                                              TRUE ~ 0),
         missing_ptv_party5 = case_when(is.na(ptv_party5) ~ 1,
                                              TRUE ~ 0),
         missing_ptv_party6 = case_when(is.na(ptv_party6) ~ 1,
                                                 TRUE ~ 0),
         missing_ptv_party7 = case_when(is.na(ptv_party7) ~ 1,
                                              TRUE ~ 0),
         missing_ptv_party8 = case_when(is.na(ptv_party8) ~ 1,
                                        TRUE ~ 0),
         missing_ptv_party9 = case_when(is.na(ptv_party9) ~ 1,
                                        TRUE ~ 0),
         missing_ptv_party10 = case_when(is.na(ptv_party10) ~ 1,
                                        TRUE ~ 0),
         missing_ptv_party11 = case_when(is.na(ptv_party11) ~ 1,
                                        TRUE ~ 0),
         missing_ptv_party12 = case_when(is.na(ptv_party12) ~ 1,
                                        TRUE ~ 0),
         missing_ptv_party13 = case_when(is.na(ptv_party13) ~ 1,
                                        TRUE ~ 0),
         missing_ptv_party14 = case_when(is.na(ptv_party14) ~ 1,
                                        TRUE ~ 0),
         missing_eu_perf_covid = case_when(is.na(eu_perf_covid) ~ 1,
                                         TRUE ~ 0),
         missing_eu_perf_econ_future = case_when(is.na(eu_perf_econ_future) ~ 1,
                                         TRUE ~ 0),
         missing_picom4 = case_when(is.na(picom4) ~ 1,
                                         TRUE ~ 0),
         missing_picom5 = case_when(is.na(picom5) ~ 1,
                                    TRUE ~ 0))
rm(mis)

df <- df %>% 
  group_by(country, wave) %>% 
  mutate(picom1 = ifelse(is.na(picom1), round(mean(picom1, na.rm=T),0), picom1),
         picom2 = ifelse(is.na(picom2), round(mean(picom1, na.rm=T),0), picom2),
         picom3 = ifelse(is.na(picom3), round(mean(picom1, na.rm=T),0), picom3),
         picom4 = ifelse(is.na(picom4), round(mean(picom1, na.rm=T),0), picom4),
         picom5 = ifelse(is.na(picom5), round(mean(picom1, na.rm=T),0), picom5),
         conspiracycovid1 = ifelse(is.na(conspiracycovid1), round(mean(conspiracycovid1, na.rm=T),0), conspiracycovid1),
         conspiracycovid2 = ifelse(is.na(conspiracycovid2), round(mean(conspiracycovid2, na.rm=T),0), conspiracycovid2),
         conspiracycovid3 = ifelse(is.na(conspiracycovid3), round(mean(conspiracycovid3, na.rm=T),0), conspiracycovid3),
         conspiracycovid4 = ifelse(is.na(conspiracycovid4), round(mean(conspiracycovid4, na.rm=T),0), conspiracycovid4),
         ptv_party1 = ifelse(is.na(ptv_party1), round(mean(ptv_party1, na.rm=T),0), ptv_party1),
         ptv_party2 = ifelse(is.na(ptv_party2), round(mean(ptv_party2, na.rm=T),0), ptv_party2),
         ptv_party3 = ifelse(is.na(ptv_party3), round(mean(ptv_party3, na.rm=T),0), ptv_party3),
         ptv_party4 = ifelse(is.na(ptv_party4), round(mean(ptv_party4, na.rm=T),0), ptv_party4),
         ptv_party5 = ifelse(is.na(ptv_party5), round(mean(ptv_party5, na.rm=T),0), ptv_party5),
         ptv_party6 = ifelse(is.na(ptv_party6), round(mean(ptv_party6, na.rm=T),0), ptv_party6),
         ptv_party7 = ifelse(is.na(ptv_party7), round(mean(ptv_party7, na.rm=T),0), ptv_party7),
         ptv_party8 = ifelse(is.na(ptv_party8), round(mean(ptv_party8, na.rm=T),0), ptv_party8),
         ptv_party9 = ifelse(is.na(ptv_party9), round(mean(ptv_party9, na.rm=T),0), ptv_party9),
         ptv_party10 = ifelse(is.na(ptv_party10), round(mean(ptv_party10, na.rm=T),0), ptv_party10),
         ptv_party11 = ifelse(is.na(ptv_party11), round(mean(ptv_party11, na.rm=T),0), ptv_party11),
         ptv_party12 = ifelse(is.na(ptv_party12), round(mean(ptv_party12, na.rm=T),0), ptv_party12),
         ptv_party13 = ifelse(is.na(ptv_party13), round(mean(ptv_party13, na.rm=T),0), ptv_party13),
         ptv_party14 = ifelse(is.na(ptv_party14), round(mean(ptv_party14, na.rm=T),0), ptv_party14),
         pid = ifelse(is.na(pid), getmode(pid), pid),
         pid_strength = ifelse(is.na(pid_strength), getmode(pid_strength), pid_strength),
         vote_recall = ifelse(is.na(vote_recall), getmode(vote_recall), vote_recall),
         vote_intention = ifelse(is.na(vote_intention), getmode(vote_intention), vote_intention),
         ideology_selfplacement = ifelse(is.na(ideology_selfplacement), round(mean(ideology_selfplacement, na.rm=T),0), ideology_selfplacement),
         ideology_placement_party1 = ifelse(is.na(ideology_placement_party1), round(mean(ideology_placement_party1, na.rm=T),0), ideology_placement_party1),
         ideology_placement_party2 = ifelse(is.na(ideology_placement_party2), round(mean(ideology_placement_party2, na.rm=T),0), ideology_placement_party2),
         ideology_placement_party3 = ifelse(is.na(ideology_placement_party3), round(mean(ideology_placement_party3, na.rm=T),0), ideology_placement_party3),
         ideology_placement_party4 = ifelse(is.na(ideology_placement_party4), round(mean(ideology_placement_party4, na.rm=T),0), ideology_placement_party4),
         ideology_placement_party5 = ifelse(is.na(ideology_placement_party5), round(mean(ideology_placement_party5, na.rm=T),0), ideology_placement_party5),
         ideology_placement_party6 = ifelse(is.na(ideology_placement_party6), round(mean(ideology_placement_party6, na.rm=T),0), ideology_placement_party6),
         gender = ifelse(is.na(gender), getmode(gender), gender),
         age = ifelse(is.na(age), round(mean(age, na.rm=T),0), age),
         education = ifelse(is.na(education), getmode(education), education),
         job = ifelse(is.na(job), getmode(job), job),
         living_situation = ifelse(is.na(living_situation), getmode(living_situation), living_situation),
         religion = ifelse(is.na(religion), round(mean(religion, na.rm=T),0), religion),
         income = ifelse(is.na(income), getmode(income), income),
         trust_others = ifelse(is.na(trust_others), round(mean(trust_others, na.rm=T),0), trust_others),
         trust_parliament = ifelse(is.na(trust_parliament), round(mean(trust_parliament, na.rm=T),0), trust_parliament),
         trust_localgov = ifelse(is.na(trust_localgov), round(mean(trust_localgov, na.rm=T),0), trust_localgov),
         trust_police = ifelse(is.na(trust_police), round(mean(trust_police, na.rm=T),0), trust_police),
         trust_healthcare = ifelse(is.na(trust_healthcare), round(mean(trust_healthcare, na.rm=T),0), trust_healthcare),
         trust_judicial = ifelse(is.na(trust_judicial), round(mean(trust_judicial, na.rm=T),0), trust_judicial),
         trust_eu = ifelse(is.na(trust_eu), round(mean(trust_eu, na.rm=T),0), trust_eu),
         covid_self = ifelse(is.na(covid_self), getmode(covid_self), covid_self),
         covid_friends = ifelse(is.na(covid_friends), getmode(covid_friends), covid_friends),
         covid_aquintances = ifelse(is.na(covid_aquintances), getmode(covid_aquintances), covid_aquintances),
         covid_none = ifelse(is.na(covid_none), getmode(covid_none), covid_none),
         tradeof_covid = ifelse(is.na(tradeof_covid), getmode(tradeof_covid), tradeof_covid),
         covid_concern = ifelse(is.na(covid_concern), round(mean(covid_concern, na.rm=T),0), covid_concern),
         gov_perf_covid = ifelse(is.na(gov_perf_covid), round(mean(gov_perf_covid, na.rm=T),0), gov_perf_covid),
         localgov_perf_covid = ifelse(is.na(localgov_perf_covid), round(mean(localgov_perf_covid, na.rm=T),0), localgov_perf_covid),
         eu_perf_covid = ifelse(is.na(eu_perf_covid), round(mean(eu_perf_covid, na.rm=T),0), eu_perf_covid),
         healthcare_perf_covid = ifelse(is.na(healthcare_perf_covid), round(mean(healthcare_perf_covid, na.rm=T),0), healthcare_perf_covid),
         economic_eval = ifelse(is.na(economic_eval), round(mean(economic_eval, na.rm=T),0), economic_eval),
         economic_prospect = ifelse(is.na(economic_prospect), round(mean(economic_prospect, na.rm=T),0), economic_prospect),
         gov_perf_econ = ifelse(is.na(gov_perf_econ), round(mean(gov_perf_econ, na.rm=T),0), gov_perf_econ),
         eu_perf_econ = ifelse(is.na(eu_perf_econ), round(mean(eu_perf_econ, na.rm=T),0), eu_perf_econ),
         eu_perf_econ_future = ifelse(is.na(eu_perf_econ_future), round(mean(eu_perf_econ_future, na.rm=T),0), eu_perf_econ_future),
         tradeof_freedom_econ = ifelse(is.na(tradeof_freedom_econ), round(mean(tradeof_freedom_econ, na.rm=T),0), tradeof_freedom_econ),
         tradeof_health_econ = ifelse(is.na(tradeof_health_econ), round(mean(tradeof_health_econ, na.rm=T),0), tradeof_health_econ),
         eu_perf_econ_future = ifelse(is.na(eu_perf_econ_future), round(mean(eu_perf_econ_future, na.rm=T),0), eu_perf_econ_future),
         tradeof_freedom_econ = ifelse(is.na(tradeof_freedom_econ), round(mean(tradeof_freedom_econ, na.rm=T),0), tradeof_freedom_econ),
         tradeof_health_econ = ifelse(is.na(tradeof_health_econ), round(mean(tradeof_health_econ, na.rm=T),0), tradeof_health_econ),
         tradeof_health_econ_party1 = ifelse(is.na(tradeof_health_econ_party1), round(mean(tradeof_health_econ_party1, na.rm=T),0), tradeof_health_econ_party1),
         tradeof_health_econ_party2 = ifelse(is.na(tradeof_health_econ_party2), round(mean(tradeof_health_econ_party2, na.rm=T),0), tradeof_health_econ_party2),
         tradeof_health_econ_party3 = ifelse(is.na(tradeof_health_econ_party3), round(mean(tradeof_health_econ_party3, na.rm=T),0), tradeof_health_econ_party3),
         tradeof_health_econ_party4 = ifelse(is.na(tradeof_health_econ_party4), round(mean(tradeof_health_econ_party4, na.rm=T),0), tradeof_health_econ_party4),
         tradeof_health_econ_party5 = ifelse(is.na(tradeof_health_econ_party5), round(mean(tradeof_health_econ_party5, na.rm=T),0), tradeof_health_econ_party5),
         tradeof_health_econ_party6 = ifelse(is.na(tradeof_health_econ_party6), round(mean(tradeof_health_econ_party6, na.rm=T),0), tradeof_health_econ_party6),
         tradeof_health_jobs = ifelse(is.na(tradeof_health_jobs), getmode(tradeof_health_jobs), tradeof_health_jobs),
         tradeof_health_freedom = ifelse(is.na(tradeof_health_freedom), getmode(tradeof_health_freedom), tradeof_health_freedom),
         beneficiaries_covid_measures = ifelse(is.na(beneficiaries_covid_measures), round(mean(beneficiaries_covid_measures, na.rm=T),0), beneficiaries_covid_measures),
         covid_measures_constitutional = ifelse(is.na(covid_measures_constitutional), round(mean(covid_measures_constitutional, na.rm=T),0), covid_measures_constitutional),
         covid_solidarity_division = ifelse(is.na(covid_solidarity_division), round(mean(covid_solidarity_division, na.rm=T),0), covid_solidarity_division),
         role_state_economy = ifelse(is.na(role_state_economy), round(mean(role_state_economy, na.rm=T),0), role_state_economy),
         impact_climate = ifelse(is.na(impact_climate), round(mean(impact_climate, na.rm=T),0), impact_climate),
         friend_enemy_USA = ifelse(is.na(friend_enemy_USA), round(mean(friend_enemy_USA, na.rm=T),0), friend_enemy_USA),
         friend_enemy_CHINA = ifelse(is.na(friend_enemy_CHINA), round(mean(friend_enemy_CHINA, na.rm=T),0), friend_enemy_CHINA),
         friend_enemy_RUSSIA = ifelse(is.na(friend_enemy_RUSSIA), round(mean(friend_enemy_RUSSIA, na.rm=T),0), friend_enemy_RUSSIA),
         belief_science = ifelse(is.na(belief_science), round(mean(belief_science, na.rm=T),0), belief_science),
         influence_science = ifelse(is.na(influence_science), round(mean(influence_science, na.rm=T),0), influence_science),
         econ_immigration = ifelse(is.na(econ_immigration), round(mean(econ_immigration, na.rm=T),0), econ_immigration),
         cult_immigration = ifelse(is.na(cult_immigration), round(mean(cult_immigration, na.rm=T),0), cult_immigration),
         gender_workforce = ifelse(is.na(gender_workforce), round(mean(gender_workforce, na.rm=T),0), gender_workforce),
         pop1 = ifelse(is.na(pop1), round(mean(pop1, na.rm=T),0), pop1),
         pop2 = ifelse(is.na(pop2), round(mean(pop1, na.rm=T),0), pop2),
         pop3 = ifelse(is.na(pop3), round(mean(pop1, na.rm=T),0), pop3),
         pop4 = ifelse(is.na(pop4), round(mean(pop1, na.rm=T),0), pop4),
         pop5 = ifelse(is.na(pop5), round(mean(pop1, na.rm=T),0), pop5),
         pop6 = ifelse(is.na(pop6), round(mean(pop1, na.rm=T),0), pop6),
         pop7 = ifelse(is.na(pop7), round(mean(pop1, na.rm=T),0), pop7)
  ) %>% 
  ungroup()
  
